export { default as care } from './about1.png';
export { default as certified} from './about2.png';
export { default as guarantee} from './about3.png';
export { default as illustration } from './about.png';
export { default as nurses } from './header-img.png';
export { default as dashed } from './dashed.png';
export { default as dotted } from './dotted.png';
export { default as aboutBg } from './about-bg.png';
export { default as oldPerson } from './about-customer.png';
export { default as chooseUs } from './choose-us.png';
export { default as chooseUsBg } from './choose-us-bg.png';